try {
    node("Linux") {
        stage('Get sources') {
            checkout scm
        }

        stage('CPT Linux stage') {
            sh 'apt-get update'
            // To build some deps from sources it needs pythonXX-dev
            sh 'apt-get -y install python3-venv python3.7-venv'
            sh 'pip install -r cpt/requirements_test.txt'
            // Show default environments
            sh 'tox -vv -l'
            sh 'tox -vv -e py37-conan-latest'
        }
    }
}
catch(e){
    echo "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'"
    throw e
}
