try {
    node("Linux") {
        sh(script: "python --version")
    }
    node("Macos") {
        sh(script: "python --version")
    }
    node("Windows") {
        bat(script: "python --version")
    }
}
catch(e){
    echo "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'"
    throw e
}